

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
// import './fontawesome.css'
import "./globals.css";
import Navbar from "@/components/header/navbar";
import FooterTwo from "@/components/footer/FooterTwo";
import FooterOne from "@/components/footer/FooterOne";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="main-wrapper">
          <Navbar />
          {children}
          <FooterOne parentClass="" />
        </main>
      </body>
    </html>
  );
}
